import { createApp } from 'vue';
import App from './App.vue';
import '@/assets/styles/tailwind.css';
import { createPinia } from 'pinia';
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate';
import i18n from './locales/index';
const app = createApp(App);
const pinia = createPinia();
pinia.use(piniaPluginPersistedstate);
app.use(pinia);
app.use(i18n);
app.mount('#app');
